platform:ios, '10.0'
inhibit_all_warnings!

target 'AccountTool' do
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'MLeaksFinder'
    pod 'Masonry'
end
